config/routes.rb
Rails.application.routes.draw do


  post 'add_to_trade' => 'trade_cart#add_to_trade'


  get 'view_trade' => 'trade_cart#view_trade'
  
  post 'delete_from_trade' => 'trade_cart#delete_from_trade'

  get 'trade' => 'trade_cart#trade'

  root 'trade#players_by_team'



  resources :teams
  resources :players


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :player
end

app/models/player.rb
class Player < ApplicationRecord

	belongs_to :team

	mount_uploader :image, ImageUploader
end

app/models/team.rb
class Team < ApplicationRecord
	has_many :players

	mount_uploader :image, ImageUploader
end

app/models/trade.rb
class Trade < ApplicationRecord

	has_many :players
	has_many :teams

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
    @teams = Team.all
  end

  # GET /players/1/edit
  def edit
    @teams = Team.all
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :team_id, :image)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
    @players = Player.new

  end

  # GET /teams/1/edit
  def edit
    @players = Player.new
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name,:image)
    end
end

app/controllers/trade_cart_controller.rb
class TradeCartController < ApplicationController
  def add_to_trade

  	line_item = LineItem.new
  	line_item.player_id = params[:player_id]
  	line_item.save
  	
  	redirect_to view_trade_url

  end

  def delete_from_trade
  	line_item = LineItem.find(params[:line_item_id])

  	line_item.destroy

  	redirect_to root_url
  	
  end

  def view_trade
  	@line_items = LineItem.all
  end

  def make_trade
	line_items = LineItem.all
	line_items.destroy_all
  
   redirect_to trade_path


  end
end

app/controllers/trade_controller.rb
class TradeController < ApplicationController
  def players_by_team
  	@players = Player.all
  	@teams = Team.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/trade_cart_helper.rb
module TradeCartHelper
end

app/helpers/trade_helper.rb
module TradeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NbaTrade</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
 

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :player_name %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.collection_select :team_id, @teams, :id, :name, id: :player_team_id %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.team.name %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @player.team_id %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/trade/players_by_team.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Trade Machine</a>
    </div>

   <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="">Players<span class="sr-only">(current)</span></a></li>
        <li class="active"><a href="#">Teams<span class="sr-only">(current)</span></a></li>
        <li class="active"><a href= "#">View Trades <span class="sr-only">(current)</span></a></li>
        
        
          
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<h1>Trade Player</h1>
<p>Pick Players to be traded</p>

<div class="row">
	<% @players.each do |player| %>
		<div class="col-sm-12 | col-md-2">
			<div class="well text-center">
				<h3><%= link_to player.team.name %></h3>
				<h3><%= link_to player.name %></h3>

				<p>
					<a href="#" data-toggle="modal" data-target="#myModal_<%= player.id %>">
						<span class="glyphicon glyphicon-transfer"></span>Trade player
					</a>
				</p>				
			</div>
      </div>	

  

		
		<div class="modal fade" id="myModal_<%= player.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= player.team.name %></h4>
      </div>
      <div class="modal-body">
      	<p>Player Name: <%= player.name %></p>
       
      </div>
      <div class="modal-footer">
      	<div style="display: inline-block;">
      		<%= form_tag add_to_trade_path, method: :post do %>
      		<%= hidden_field_tag :player_id, player.id %>
      		<%= submit_tag "Add to Trade", class: "btn btn-primary", style: "display: inline-block;" %>
      		<% end %>      		
      	</div>
      	<div style="display: inline-block;">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      </div>
    </div>
  </div>

	<% end %>	
</div>
 

app/views/trade_cart/add_to_trade.html.erb
<h1>TradeCart#add_to_trade</h1>
<p>Find me in app/views/trade_cart/add_to_trade.html.erb</p>

app/views/trade_cart/trade.html.erb
<h1>Trade was Successful</h1>

app/views/trade_cart/view_trade.html.erb
<h2>Players up for Trade</h2>

<div>
	<table class="table">
		<thead>
			<tr>
				<th>Player</th>
			</tr>
		</thead>
		<tbody>
			<% @line_items.each do |line_item| %>
			<tr>
				<td><%= line_item.player.name %></td>
				<td><%= link_to "Delete Item", delete_from_trade_path(line_item_id: line_item.id), method: :post, class: "btn btn_danger", data: { confrim: "Are your sure?"} %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

<%= link_to "Proceed with Trade", trade_path, class: "btn btn-success" %>
<%= link_to "Look for another player to trade", root_path, class: "btn btn-info" %>